Added HW15.cpp file
shintanshin/GameDev_Cpp_Course pull request #9
Opened 2023-12-26 09:45 UTC by shintanshin

Please review my 15th homework.

2023-12-28 20:06 UTC, bohdanpc requested changes

2023-12-28 20:06 UTC, bohdanpc commented on HW15/HW15.cpp
> +    return static_cast <double> (sum) / 4.0;
unsigned divided by double is double, so cast is redundant here.

2023-12-28 20:06 UTC, bohdanpc commented on HW15/HW15.cpp
> +    for (int i = 0; i < 4; ++i) {
please extract this 4 into const and use it everywhere instead

2023-12-28 20:06 UTC, bohdanpc commented on HW15/HW15.cpp
> +        if (averageMark(students[i]) > averageMark(*mostSuccessful)) {
no need to calculate average of mostSuccessful student every iteration.
can `cache` (read pre-save) mostSuccessfulMark and use it in comparison to reduce average calculations amount

2024-01-10 18:27 UTC, helen-black approved these changes

2024-01-11 12:25 UTC, merged